### PR TITLE
Add annotation types parameter

### PR DESCRIPTION
**Pull request by paulbriton**
This change reflects the changes in the GATE Python Plugin to support the GATE inline XML output. Check this [PR](https://github.com/GateNLP/gateplugin-Python/pull/68) for more details.

### CODE REVIEW

**Comment by johann-petrak** [comment]
Thank you very much for that PR. 

First off, I am not sure if 

Could I please ask you to:
* please do not change the kernel name in the notebooks in the doc directory but rather use a kernel with the name stored there
* please do not use a mutable value like `[]` as the default parameter, instead use `None` to indicate using all types and require the explicity specification of `[]` to specify no types. 
* please use "text/xml" to indicate inline XML format
* Since the parameter is specific to the XML inline format, I would suggest to call the parameter `inline_anntypes` as we might want to have a similar parameter for more general use later.
* This always uses the annotations from the default set, so to specify which set to use a parameter `inline_annset` could be added which defaults to "" indicating the default set.
* to fully support the inline XML format, `inline_features=True` could also be added
* on the Java side I would suggest to keep the `saveDocumentToFile(Document doc, String path, String mimetype)` method and add `saveDocumentToFile(Document doc, String path, String mimetype, List<String> inline_anntypes, String inline_annset, boolean inline_features)` to which  `saveDocumentToFile(Document doc, String path, String mimetype)`  delegates with default values for the new parameters. 

Let me know what you think of those changes. 

Sorry for those additional points, we usually recommend to discuss planned changes in an issue first and then agree on how to implement the solution.

**Comment by paulbriton** [comment]
Thank you very much for your quick answer! I'm sorry that I didn't open an issue first to discuss these changes... To be honest, I'm currently using this in a project and I was tweaking a fork of the lib. Once I got it working locally I realized it would be better for my project if these changes were merged in the official repo.

I'll integrate the suggested changes and get back to you!

**Comment by paulbriton** [comment]
I've pushed the modifications. Let me know if these changes match what you had in mind!

**Comment by johann-petrak** [comment]
I have merged this, but there are still issues.  I will try to find the time to fix them, probably faster than going back and forth here.

**Comment by paulbriton** [comment]
Thanks again, let me know when you'll have the time to fix the remaining issues and to make a new release!

**Comment by johann-petrak** [comment]
This is now implemented in the development versions of gateplugin-Python and gatenlp 

Behavior has changed so that `inline_anntypes=None` will export ALL types from the set, while `inline_anntypes=[]` will export none so it is easy to choose any set.

**Pull request merged**
